<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TestAccountKaryawan1_c-avatar-img</name>
   <tag></tag>
   <elementGuidId>89995db3-366f-483e-ba82-d43a39d9189f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png' and @alt = 'admin@bootstrapmaster.com']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/ul/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.c-avatar-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>824e7ec0-c295-4049-94e7-f0bba61ca8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-avatar-img</value>
      <webElementGuid>66cd1ee3-e350-47e9-ba81-8b9347c3cac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png</value>
      <webElementGuid>0afaf179-ce2c-4e6c-9f08-6435ca155cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>admin@bootstrapmaster.com</value>
      <webElementGuid>880b7df6-8ce2-42ff-9807-029d6fb74b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;c-app c-default-layout&quot;]/div[@class=&quot;c-sidebar c-sidebar-dark c-sidebar-lg-show c-sidebar-fixed sidebar-root&quot;]/ul[@class=&quot;c-sidebar-nav h-100 ps&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center mt-3 mb-5 px-3&quot;]/div[@class=&quot;c-avatar&quot;]/img[@class=&quot;c-avatar-img&quot;]</value>
      <webElementGuid>3651cd49-44c3-42eb-829b-dd692d9048ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/ul/div/div/img</value>
      <webElementGuid>28afe163-78a0-47c4-bc65-e303103c3291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='admin@bootstrapmaster.com']</value>
      <webElementGuid>35cfefe8-193f-4971-b84d-f6bb59041785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/div/img</value>
      <webElementGuid>bbe19d20-9e02-4833-9409-d8285d28d2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://103.180.125.58:11000/media/uploads/images/img_61b1a6bb45_profil user.png' and @alt = 'admin@bootstrapmaster.com']</value>
      <webElementGuid>5a06b28c-07ce-40dc-aecf-1909236d9f52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
